CREATE TABLE `crm_trigger_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`triggerId` int NOT NULL,
	`leadId` int,
	`eventData` json,
	`actionsExecuted` json,
	`status` enum('success','partial','failed') DEFAULT 'success',
	`executedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `crm_trigger_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `crm_triggers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(256) NOT NULL,
	`description` text,
	`isActive` boolean DEFAULT true,
	`eventType` enum('lead_created','stage_change','website_visit','form_submit','email_opened','email_replied','inactivity','score_threshold','tag_added','manual') NOT NULL,
	`conditions` json,
	`actions` json,
	`executionCount` int DEFAULT 0,
	`lastExecutedAt` timestamp,
	`createdByUserId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `crm_triggers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `crm_website_visitors` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sessionId` varchar(128) NOT NULL,
	`ipAddress` varchar(64),
	`companyName` varchar(256),
	`companyDomain` varchar(256),
	`companyIndustry` varchar(128),
	`companySize` varchar(32),
	`companyRevenue` varchar(64),
	`companyLinkedIn` varchar(512),
	`city` varchar(128),
	`country` varchar(64),
	`pagesViewed` json,
	`totalPageViews` int DEFAULT 1,
	`totalVisits` int DEFAULT 1,
	`firstVisitAt` timestamp NOT NULL DEFAULT (now()),
	`lastVisitAt` timestamp NOT NULL DEFAULT (now()),
	`referrer` varchar(512),
	`utmSource` varchar(128),
	`utmMedium` varchar(128),
	`utmCampaign` varchar(128),
	`matchedLeadId` int,
	`enrichmentData` json,
	`isIdentified` boolean DEFAULT false,
	`status` enum('new','identified','matched','outreach_sent','ignored') DEFAULT 'new',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `crm_website_visitors_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `member_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`companyId` int,
	`tier` enum('prospect','vergaderen','gebaloteerd') NOT NULL DEFAULT 'prospect',
	`displayName` varchar(256) NOT NULL,
	`email` varchar(320),
	`phone` varchar(20),
	`companyName` varchar(256),
	`jobTitle` varchar(128),
	`linkedIn` varchar(512),
	`photoUrl` text,
	`locationPreference` varchar(128),
	`creditBalance` decimal(12,2) DEFAULT '0',
	`creditBundleType` varchar(64),
	`totalBookings` int DEFAULT 0,
	`totalSpent` decimal(12,2) DEFAULT '0',
	`lastActiveAt` timestamp,
	`ballotDate` timestamp,
	`ballotSponsor` varchar(256),
	`source` varchar(128),
	`funnelStage` varchar(64),
	`notes` text,
	`tags` json,
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `member_profiles_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `reengagement_funnel` (
	`id` int AUTO_INCREMENT NOT NULL,
	`memberProfileId` int,
	`contactName` varchar(256) NOT NULL,
	`contactEmail` varchar(320),
	`companyName` varchar(256),
	`previousRelationship` varchar(128),
	`stage` enum('identified','invited','opened','applied','interview','accepted','declined') NOT NULL DEFAULT 'identified',
	`inviteSentAt` timestamp,
	`inviteOpenedAt` timestamp,
	`applicationDate` timestamp,
	`personalMessage` text,
	`aiGeneratedInvite` text,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `reengagement_funnel_id` PRIMARY KEY(`id`)
);
